#!/bin/bash
set -e

case "$1" in
    configure)
        pip3 install --quiet --break-system-packages --ignore-installed \
            "discord.py[voice]" \
            python-dotenv \
            "tomlkit>=0.13.0" \
            ollama \
            google-genai \
            groq \
            InquirerPy
        ;;
esac

exit 0
