ai = {
    "activate_ai": False,
    "provider": "groq",
    "model": "qwen/qwen3-32b",
    "max_messages_context": 10,
    "remove_emojis": True,
    "lower_response": True,
    "answer_to_reply": False,
    "include_username": True,
    "include_reply": True,
    "include_attachment": True,
    "system_prompt": "You are a helpful assistant that gives short, helpful answers.\nYour answers can maximally be 1000 characters long.\n",
    "user_prompt": "{{USERNAME}} wrote the following message: {{MESSAGE}}\n",
    "user_reply_prompt": "They added the following context: {{REPLY}}\n",
    "user_attachement_prompt": "The user attached the following file: {{FILE}}\n",
    "user_prompt_structure": "{{PROMPT}}\n\n{{REPLY_PROMPT}}\n\n{{ATTACHMENT_PROMPT}}\n",
}

config = {
    "prefix": "!",
    "money_symbol": "$",
    "ascii_art": ["¯\\_(ツ)_/¯"],
    "bot_admins": [],
    "debug_mode": False,
    "whitelist": [],
    "whitelist_mode": False,
}

error_messages = {
    "quote": "Failed to get a quote.",
    "joke": "Failed to get a joke.",
    "meme": "Failed to get a meme.",
    "waifu": "Failed to get a waifu image.",
    "duck": "Failed to get a duck image.",
    "dog": "Failed to get a dog image.",
    "cat": "Failed to get a cat image.",
    "chuck": "Failed to get a Chuck Norris joke.",
    "fact": "Failed to get a fact.",
    "bible": "Failed to get a bible verse.",
    "passage_not_found": "Couldn't find bible passage: {{PASSAGE}}",
    "truth": "Failed to get a truth question.",
    "dare": "Failed to get a dare question.",
    "wyr": "Failed to get a Would You Rather question.",
    "never-hie": "Failed to get a Never Have I Ever question.",
    "paranoia": "Failed to get a paranoia question.",
    "trivia": "Failed to get a trivia question.",
    "calculate": "Invalid calculation. Use +-*/",
    "bitcoin": "Failed to get the current bitcoin price.",
    "currency": "Unknown currency.",
    "unavailable": "API unavailable.",
    "unknown_command": "Unknown command.",
    "unknown_argument": "Unknown argument.",
    "missing_argument": "Missing argument.",
    "no_attachment": "No attachment given.",
    "bot_unavailable": "Bot not available.",
    "unknown_category": "Unknown category.",
    "no_ascii_art": "No ASCII art available.",
    "unknown_unit": "Unknown unit: {{UNIT}}",
}

keywords = {
    "general": {
        "quote": ["quote"],
        "joke": ["joke"],
        "meme": ["meme"],
        "waifu": ["waifu"],
        "duck": ["duck"],
        "dog": ["dog"],
        "cat": ["cat"],
        "chuck_norris": ["chuck", "norris", "chucknorris"],
        "fact": ["fact"],
        "bible": ["bible"],
        "calculate": ["calculate", "calc"],
        "bitcoin": ["bitcoin", "btc"],
        "currency": ["currency", "convert", "conv"],
        "qr_code": ["qr_code", "qr"],
        "reminder": ["reminder", "remind", "todo"],
        "ascii_art": ["ascii", "art"],
        "help": ["help"],
        "truth": ["truth"],
        "dare": ["dare"],
        "wyr": ["wyr"],
        "never_have_i_ever": ["never-have-i-ever", "nhie"],
        "paranoia": ["paranoia"],
        "trivia": ["trivia", "quiz", "question"],
    },
    "settings": {
        "settings": ["config", "set", "settings"],
        "profile_picture": ["pfp", "picture", "pic"],
        "banner": ["banner"],
        "change_name": ["name", "nickname"],
        "change_keywords": ["keywords", "key"],
    },
    "money": {
        "add_money": ["add", "add_money"],
        "remove_money": ["subtract", "sub", "remove_money"],
        "check_balance": ["check", "check_balance", "balance"],
    },
}

moderation = {
    "delete": [],
    "kick": [],
    "ban": [],
    "mute": [],
    "time_to_mute": 5,
}

active = {
    "general": {
        "quote": True,
        "joke": True,
        "meme": True,
        "waifu": True,
        "duck": True,
        "dog": True,
        "cat": True,
        "chuck_norris": True,
        "fact": True,
        "bible": True,
        "calculate": True,
        "bitcoin": True,
        "currency": True,
        "qr_code": True,
        "reminder": True,
        "help": True,
        "truth": True,
        "dare": True,
        "wyr": True,
        "never_have_i_ever": True,
        "paranoia": True,
        "trivia": True,
        "nsfw": False,
        "purge": True,
    },
}

descriptions = {
    "general": {
        "quote": "Get a random inspirational quote.",
        "joke": "Get a random two-part joke",
        "meme": "Get a random meme image",
        "waifu": "Compare two random waifu images",
        "duck": "Get a random duck image",
        "dog": "Get a random dog image",
        "cat": "Get a random cat image",
        "chuck_norris": "Get a random Chuck Norris fact",
        "fact": "Get a random fun fact",
        "bible": "Get a random or specific Bible verse",
        "calculate": "Evaluate a math expression",
        "bitcoin": "Get the current Bitcoin price in a given currency",
        "currency": "Convert an amount between two currencies",
        "qr_code": "Generate a QR code from a URL",
        "reminder": "Set a reminder for a specific time",
        "ascii_art": "Display the bot's ASCII art",
        "help": "Show available commands",
        "truth": "Get a truth question for truth or dare",
        "dare": "Get a dare challenge for truth or dare",
        "wyr": "Get a would you rather question",
        "never_have_i_ever": "Get a never have I ever prompt",
        "paranoia": "Get a paranoia question",
        "trivia": "Get a multiple-choice trivia question",
        "purge": "Delete all messages in the channel (admin only)",
    },
    "settings": {
        "settings": "Configure the bot",
        "profile_picture": "Change the bot's profile picture",
        "banner": "Change the bot's banner",
        "change_name": "Change the bot's username",
        "change_keywords": "Change a command's trigger keywords",
    },
    "money": {
        "check_balance": "Check a user's money balance",
        "add_money": "Add money to a user's balance (admin only)",
        "remove_money": "Remove money from a user's balance (admin only)",
    },
}

output = {
    "general": {
        "quote": ["{{QUOTE}}\n~ {{AUTHOR}}"],
        "joke": ["{{SETUP}} ||{{PUNCHLINE}}||"],
        "meme": ["{{URL}}"],
        "waifu": ["### Which one is the better waifu? \n ![]({{URL1}}) ![]({{URL2}})"],
        "duck": ["{{URL}}"],
        "dog": ["{{URL}}"],
        "cat": ["{{URL}}"],
        "chuck_norris": ["{{JOKE}}"],
        "fact": ["{{FACT}}"],
        "bible": ["{{PASSAGE}}\n{{BOOK}} {{CHAPTER}}:{{VERSE}}"],
        "calculate": ["{{RESULT}}"],
        "bitcoin": ["The bitcoin price is currently at {{AMOUNT}} {{CURRENCY}}."],
        "currency": ["{{FROM_AMOUNT}} {{FROM_CURRENCY}} = {{TO_AMOUNT}} {{TO_CURRENCY}}"],
        "qr_code": ["{{URL}}"],
        "reminder": ["Reminder set in {{TIME}}"],
        "ascii_art": ["{{ASCII_ART}}"],
        "truth": ["{{QUESTION}}"],
        "dare": ["{{QUESTION}}"],
        "wyr": ["{{QUESTION}}"],
        "never_have_i_ever": ["{{QUESTION}}"],
        "paranoia": ["{{QUESTION}}"],
        "trivia": ["## {{QUESTION}}\n1. {{CHOICE1}}\n2. {{CHOICE2}}\n3. {{CHOICE3}}\n4. {{CHOICE4}}\n\n-# Difficulty: {{DIFFICULTY}}\n-# Category: {{CATEGORY}}"],
    },
    "settings": {
        "profile_picture_applied": ["Profile picture applied successfully."],
        "banner_applied": ["Banner applied successfully."],
        "nickname_applied": ["Name '{{NAME}}' applied successfully."],
        "keywords_applied": ["Custom keywords '{{KEYWORDS}}' for the command '{{COMMAND}}' applied successfully!"],
    },
    "money": {
        "add_money": ["{{AMOUNT}}{{MONEY_SYMBOL}} added to to the account of {{USERNAME}}. They now have {{BALANCE}}{{MONEY_SYMBOL}}."],
        "remove_money": ["{{AMOUNT}} subtracted from the account of {{USERNAME}}. They now have {{BALANCE}}{{MONEY_SYMBOL}}."],
        "check_balance": ["The balance of the account from {{USERNAME}} is currently {{BALANCE}}{{MONEY_SYMBOL}}."],
        "insufficient_funds": ["{{USERNAME}} doesn't have enough money. They now have {{BALANCE}}{{MONEY_SYMBOL}}."],
    },
    "moderation": {
        "delete": ["Your message was deleted because it contains banned text: {{TEXT}}"],
        "kick": ["Your account was kicked because your message contains banned text: {{TEXT}}"],
        "ban": ["Your account was banned because your message contains banned text: {{TEXT}}"],
        "mute": ["Your account was muted for {{MINUTES}} minutes because your message contains banned text: {{TEXT}}"],
        "reason": "Sending banned text",
    },
}

env = "BOT_TOKEN=\nGEMINI=\nGROQ=\n"
